name: Test

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test:
    name: test (terraform ${{ matrix.terraform }}, sops ${{ matrix.sops }})
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.13"
          - "1.14"
        sops:
          - "3.11.0"

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: "go.mod"
          cache: true

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.terraform }}.*
          terraform_wrapper: false

      - name: Install SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v${{ matrix.sops }}/sops-v${{ matrix.sops }}.linux.amd64
          sudo mv sops-v${{ matrix.sops }}.linux.amd64 /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops

      - run: |
          go mod download

      - run: |
          go test -v
        timeout-minutes: 10
        env:
          TF_ACC: "1"
